name: Build and deploy site

# Controls when the workflow will run
on:
  push:
    branches: [ web-new ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install python3
        uses: actions/setup-python@v3.0.0
        with:
          cache: 'pip'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Build site
        run: python3 build.py

      - name: Build lottery cars page
        run: python3 lotterycars.py

      - name: Build stock perf page
        run: python3 stockperf.py

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          BRANCH: gh-pages
          FOLDER: build
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          git-config-name: Github Actions
          git-config-email: gh.ddm999@gmail.com

#      - name: Add CNAME for gtinfo
#        run: python3 cname-make.py
#
#      - name: Pushes to another repository
#        uses: cpina/github-action-push-to-another-repository@main
#        env:
#          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#        with:
#          source-directory: 'build'
#          destination-github-username: 'ddm999'
#          destination-repository-name: 'gtinfo'
#          user-name: 'ddm999'
#          user-email: gh.ddm999@gmail.com
#          target-branch: gh-pages
